export type OwnedUploadedObject =
    | { kind: 'user'; fileName: string }
    | { kind: 'project'; fileName: string; projectId: string };

/**
 * Object keys are generated by the storage service, not supplied as arbitrary
 * URLs. Accept only the two owner-scoped layouts emitted by uploadFileAction.
 */
export function parseOwnedUploadedObjectKey(
    fileName: string,
    userId: string
): OwnedUploadedObject | null {
    if (!fileName || !userId) return null;

    const userPrefix = `users/${userId}/uploads/`;
    if (fileName.startsWith(userPrefix)) {
        const leaf = fileName.slice(userPrefix.length);
        if (leaf && !leaf.includes('/')) return { kind: 'user', fileName };
    }

    const projectMatch = /^projects\/([^/]+)\/([^/]+)$/.exec(fileName);
    if (projectMatch?.[1] && projectMatch[2]) {
        return {
            kind: 'project',
            projectId: projectMatch[1],
            fileName,
        };
    }

    return null;
}
