import { GuardError, requireOwnedProject, requireUser, type AuthContext } from '@/lib/guards';
import { getStorageService } from '@/lib/storage/service';
import { parseOwnedUploadedObjectKey } from '@/lib/uploaded-object-key';

export type ReadableUploadedObject = {
    fileName: string;
    authCtx: AuthContext;
};

/**
 * A document record must point back to an object key generated by the upload
 * service. Old records that only contain an arbitrary URL are intentionally
 * not fetched: they need to be uploaded again so the source can be bound to
 * the current owner.
 */
export const DOCUMENT_SOURCE_UNAVAILABLE_MESSAGE = '文档源文件不可用，请重新上传后重试';
export const DOCUMENT_SOURCE_RETRY_MESSAGE = '暂时无法读取文档源文件，请稍后重试';

/**
 * Enforces ownership before an uploaded object can be read or converted to a
 * signed URL. This is intentionally a normal server helper rather than a
 * Server Action so parsers and API routes cannot accidentally reintroduce an
 * arbitrary-URL fetch path.
 */
export async function requireReadableUploadedObjectForOwner(
    fileName: string,
    providedAuthCtx?: AuthContext
): Promise<ReadableUploadedObject> {
    const authCtx = providedAuthCtx ?? (await requireUser());
    const object = parseOwnedUploadedObjectKey(fileName, authCtx.userId);
    if (!object) throw new GuardError(404, '文件不存在或无权访问');

    if (object.kind === 'project') {
        await requireOwnedProject(object.projectId, authCtx);
    }

    return { fileName: object.fileName, authCtx };
}

export async function getReadableUploadedObjectUrlForOwner(
    fileName: string,
    providedAuthCtx?: AuthContext
) {
    const object = await requireReadableUploadedObjectForOwner(fileName, providedAuthCtx);
    return getStorageService().getFileUrl(object.fileName);
}

export async function getReadableUploadedObjectBufferForOwner(
    fileName: string,
    providedAuthCtx?: AuthContext
) {
    const object = await requireReadableUploadedObjectForOwner(fileName, providedAuthCtx);
    return getStorageService().getObjectBuffer(object.fileName);
}

/**
 * Resolve a document's source through the owner-scoped storage boundary.
 * Do not fall back to Document.url here: that field is historical metadata
 * and must never be allowed to select a server-side network destination.
 */
export async function getReadableDocumentSourceUrlForOwner(
    documentFileName: unknown,
    providedAuthCtx?: AuthContext
) {
    const authCtx = providedAuthCtx ?? (await requireUser());
    const fileName = typeof documentFileName === 'string' ? documentFileName.trim() : '';

    if (!parseOwnedUploadedObjectKey(fileName, authCtx.userId)) {
        throw new GuardError(409, DOCUMENT_SOURCE_UNAVAILABLE_MESSAGE);
    }

    try {
        return await getReadableUploadedObjectUrlForOwner(fileName, authCtx);
    } catch (error) {
        if (error instanceof GuardError) {
            if (error.status === 401) throw error;
            throw new GuardError(409, DOCUMENT_SOURCE_UNAVAILABLE_MESSAGE);
        }
        throw new GuardError(503, DOCUMENT_SOURCE_RETRY_MESSAGE);
    }
}
