'use client';

import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import EditorToolbar from './toolbar/editor-toolbar';
import { useEffect, useRef, useState } from 'react';
import LineNumber from './extensions/line-number'; // 需要创建此扩展
import { useSourceEditor, useTargetEditor, useEditorContent } from '@/hooks/useEditor';
import { useTranslationContent } from '@/hooks/useTranslation';
import { getEditorContentSyncDecision } from '@/lib/editor-content-sync';
import { resolveRichTextEditorSaveFailure } from '@/lib/ide-client-error';
import {
    getContentByIdAction,
    savePostEditReviewDraftAction,
    updateOriginalTextAction,
} from '@/actions/document-item';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Pencil } from 'lucide-react';
import { useTranslations } from 'next-intl';
// 修改编辑器组件接口
interface EditorProps {
    editorId: string;
    initialContent: string;
    placeholder?: string;
    job: 'rawtext' | 'translation';
    readOnly?: boolean;
    onUpdate?: (editor: any) => void;
}

// 单个富文本编辑器组件
const RichTextEditor = ({
    editorId, // 编辑器ID，通常是documentItem的id
    initialContent, // 初始内容
    placeholder, // 提示
    job, // 编辑器类型
    readOnly = false, // 是否只读
}: EditorProps) => {
    const t = useTranslations('IDE.editor');
    const { editor: sourceEditor, setEditor: setSourceEditor } = useSourceEditor();
    const { editor: targetEditor, setEditor: setTargetEditor } = useTargetEditor();
    const { content, setContent } = useEditorContent(job === 'rawtext' ? 'source' : 'target');
    const {
        contentItemId,
        sourceText,
        persistedTargetText,
        setPersistedTargetTranslationText,
        setSourceTranslationText,
        setTargetTranslationText,
    } = useTranslationContent();
    const [isEditMode, setIsEditMode] = useState<boolean>(false);
    const lastLocalContentRef = useRef<string | null>(null);
    const syncedEditorIdRef = useRef<string | null>(null);
    const contentItemIdRef = useRef(contentItemId);
    contentItemIdRef.current = contentItemId;
    const effectiveEditable = isEditMode && !readOnly;
    const editor = useEditor({
        extensions: [
            StarterKit as any,
            // LineNumber.configure({
            //     showLineNumbers: true,
            // }),
        ],
        editorProps: {
            attributes: {
                class: 'prose prose-sm sm:prose lg:prose-lg xl:prose-2xl mx-auto focus:outline-none line-numbers overflow-auto size-full',
                'data-deeptrans-editor-item-id': editorId,
                'data-deeptrans-editor-job': job,
                'data-deeptrans-editor-dirty': 'false',
            },
        },
        content: initialContent || '',
        editable: effectiveEditable,
        onUpdate: ({ editor }) => {
            const newContent = editor.getHTML();
            lastLocalContentRef.current = newContent;
            editor.view.dom.setAttribute('data-deeptrans-editor-dirty', 'true');
            setContent(newContent);
            if (job === 'rawtext') {
                setSourceTranslationText(newContent);
            } else {
                setTargetTranslationText(newContent);
            }
        },
        immediatelyRender: false,
    });

    // 切换编辑模式时同步 TipTap 的 editable 状态
    useEffect(() => {
        if (editor) {
            editor.setEditable(effectiveEditable);
            if (effectiveEditable) {
                try {
                    editor.chain().focus().run();
                } catch {}
            }
        }
    }, [editor, effectiveEditable]);

    // Only apply real external content changes. Redux echoes generated by this
    // editor must not reset TipTap (and therefore its selection/composition).
    useEffect(() => {
        if (!editor) return;

        const incomingContent = String(initialContent ?? '');
        const decision = getEditorContentSyncDecision({
            previousEditorId: syncedEditorIdRef.current,
            editorId,
            incomingContent,
            lastLocalContent: lastLocalContentRef.current,
            currentEditorContent: editor.getHTML(),
        });

        if (decision.shouldSetEditorContent) {
            editor.commands.setContent(incomingContent, { emitUpdate: false });
        }
        if (decision.shouldSyncStore) {
            setContent(incomingContent);
        }

        syncedEditorIdRef.current = editorId;
        if (!decision.isLocalEcho) {
            lastLocalContentRef.current = incomingContent;
            editor.view.dom.setAttribute('data-deeptrans-editor-dirty', 'false');
        }
    }, [editor, editorId, initialContent, setContent]);

    // 设置编辑器实例
    useEffect(() => {
        if (editor) {
            if (job === 'rawtext') {
                setSourceEditor(editor);
            } else if (job === 'translation') {
                setTargetEditor(editor);
            }
        }
        return () => {
            if (job === 'rawtext') {
                setSourceEditor(null);
            } else if (job === 'translation') {
                setTargetEditor(null);
            }
        };
    }, [editor, job]);

    const handleSave = async () => {
        const visibleContent = editor?.getHTML() ?? content;
        if (job === 'translation' && contentItemIdRef.current !== String(editorId)) {
            toast.error(t('saveSegmentChanged'));
            return;
        }

        try {
            if (job === 'rawtext') {
                await updateOriginalTextAction(editorId, visibleContent);
                toast.success(t('saveRawSuccess'));
                try {
                    const fresh = await getContentByIdAction(editorId);
                    const next = fresh?.sourceText ?? visibleContent;
                    setSourceTranslationText(next);
                    try {
                        editor?.commands.setContent(next);
                    } catch {}
                } catch {
                    // 回退到本地内容
                    try {
                        setSourceTranslationText(visibleContent);
                    } catch {}
                }
            } else if (job === 'translation') {
                const saved = await savePostEditReviewDraftAction(editorId, {
                    expectedSourceText: String(sourceText || ''),
                    expectedTargetText: String(persistedTargetText || ''),
                    targetText: visibleContent,
                });
                // An old editor response must not replace the text/snapshot of
                // the segment the user has since opened.
                if (contentItemIdRef.current !== String(editorId)) return;
                const next = String(saved.targetText || '');
                lastLocalContentRef.current = next;
                editor?.view.dom.setAttribute('data-deeptrans-editor-dirty', 'false');
                setContent(next);
                setTargetTranslationText(next);
                setPersistedTargetTranslationText(next);
                try {
                    editor?.commands.setContent(next, { emitUpdate: false });
                } catch {}
                toast.success(t('saveTransSuccess'));
            }
            setIsEditMode(false);
        } catch (error) {
            const saveFailure = resolveRichTextEditorSaveFailure(error);
            toast.error(
                saveFailure === 'changed-elsewhere'
                    ? t('saveChangedElsewhere')
                    : saveFailure === 'review-state-changed'
                      ? t('saveReviewStateChanged')
                      : t('saveFailed')
            );
        }
    };

    if (!editor) return null;

    return (
        <div className="relative size-full rounded-b-md">
            {isEditMode && <EditorToolbar editor={editor} onSave={handleSave} />}
            {!isEditMode && !readOnly && (
                <div className="absolute right-1 top-1 z-20">
                    <Button
                        variant="secondary"
                        size="sm"
                        className="h-7 border border-border/60 bg-background/80 px-2 text-foreground shadow-sm backdrop-blur-sm"
                        onClick={() => setIsEditMode(true)}
                    >
                        <Pencil className="mr-1 h-4 w-4" /> {t('edit')}
                    </Button>
                </div>
            )}
            <div className="editor-container relative h-full p-2">
                <EditorContent className="prose overflow-auto bg-card" editor={editor} />
            </div>
        </div>
    );
};

export default RichTextEditor;
