import { auth } from '@/auth'
import { prisma } from "@/lib/db";
import { NextRequest, NextResponse } from 'next/server'
export async function GET(
  req: NextRequest,
  context: { params: Promise<{ id: string }> }  // ✅ 正确：params 是 Promise
) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return Response.json({ error: '未授权' }, { status: 401 });
    }

    const {id: projectId} = await context.params;

    // 验证项目所有权
    const project = await prisma.project.findUnique({
      where: { id: projectId },
      select: { userId: true }
    });
    
    if (!project) {
      return Response.json({ error: '项目不存在' }, { status: 404 });
    }
    
    if (project.userId && project.userId !== session.user.id) {
      return Response.json({ error: '无权操作' }, { status: 403 });
    }
    
    // 获取项目关联的词典
    const projectDictionaries = await prisma.projectDictionary.findMany({
      where: { projectId },
      include: {
        dictionary: {
          include: {
            projectBindings: {
              select: { projectId: true }
            },
            entries: {
              select: { id: true }
            }
          }
        }
      }
    });
    
    // 格式化响应数据
    const dictionaries = projectDictionaries.map((binding: any) => {
      const dict = binding.dictionary;
      const isShared = dict.projectBindings.length > 1;
      
      return {
        id: dict.id,
        name: dict.name,
        description: dict.description,
        visibility: dict.visibility,
        entryCount: dict.entries.length,
        isShared,
        isAutoGenerated: dict.name.includes('术语清单'),
        createdAt: dict.createdAt,
        updatedAt: dict.updatedAt
      };
    });
    
    return Response.json(dictionaries);
    
  } catch (error) {
    console.error('获取项目词典失败:', error);
    return Response.json(
      { error: '获取失败', details: error instanceof Error ? error.message : '未知错误' },
      { status: 500 }
    );
  }
}